site_name: Sushil Bhingardive
site_description: A blog about technology and programming
site_url: https://mydomain.org/mysite
theme:
  name: material
  font:
  text: Roboto
  palette: 
   # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: blue
      accent: blue
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
      primary: blue
      accent: deep orange
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigration.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - navigation.footer

plugins:
  - search
  - blog:
      post_url_format: "{slug}"
      
  - tags:
      listings_map:
        scoped:
          scope: true
          
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

hooks:
    - hooks\socialmedia.py


nav:
    - Home: index.md
    - DevKit:
      - Cheat Sheets: DevKit/cheat-sheets.md
    - Articles:
      - AI: Articles/ai.md
    - Blog:
      - blog/index.md
    - Tags: tags.md
    - Resources:
      - Books: Resources/books.md
    - About Me: about.md
